#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AI_Skill_Vendetta_Playstyle

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AI_Skill_Vendetta_Playstyle.AI_Skill_Vendetta_Playstyle_C
// 0x0000 (0x0148 - 0x0148)
class UAI_Skill_Vendetta_Playstyle_C final : public UFortAthenaAIBotPlayStyleSkillSet
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AI_Skill_Vendetta_Playstyle_C">();
	}
	static class UAI_Skill_Vendetta_Playstyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAI_Skill_Vendetta_Playstyle_C>();
	}
};

}

