#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Assets_ClientAsset

#include "Basic.hpp"

#include "Assets_ClientAsset_classes.hpp"


namespace SDK
{

// Function Assets_ClientAsset.ClientAsset.$InitCDO
// ()

void UClientAsset::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ClientAsset", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Assets_ClientAsset.ClientAsset.$InitInstance
// ()

void UClientAsset::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ClientAsset", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}

}

