#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Athena_Player_SneakySnowmanV2

#include "Basic.hpp"

#include "Athena_Player_SneakySnowmanV2_classes.hpp"
#include "Athena_Player_SneakySnowmanV2_parameters.hpp"


namespace SDK
{

// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.ExecuteUbergraph_Athena_Player_SneakySnowmanV2
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::ExecuteUbergraph_Athena_Player_SneakySnowmanV2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "ExecuteUbergraph_Athena_Player_SneakySnowmanV2");

	Params::Athena_Player_SneakySnowmanV2_C_ExecuteUbergraph_Athena_Player_SneakySnowmanV2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.PlayerDied
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DamagedActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AController*                      InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   HitLocation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              FHitComponent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             BoneName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Momentum                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::PlayerDied(class AActor* DamagedActor, float Damage, class AController* InstigatedBy, class AActor* DamageCauser, const struct FVector& HitLocation, class UPrimitiveComponent* FHitComponent, class FName BoneName, const struct FVector& Momentum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "PlayerDied");

	Params::Athena_Player_SneakySnowmanV2_C_PlayerDied Parms{};

	Parms.DamagedActor = DamagedActor;
	Parms.Damage = Damage;
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;
	Parms.HitLocation = std::move(HitLocation);
	Parms.FHitComponent = FHitComponent;
	Parms.BoneName = BoneName;
	Parms.Momentum = std::move(Momentum);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.DBNO
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPawn*                        FortPawn                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInIsDBNO                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::DBNO(class AFortPawn* FortPawn, bool bInIsDBNO)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "DBNO");

	Params::Athena_Player_SneakySnowmanV2_C_DBNO Parms{};

	Parms.FortPawn = FortPawn;
	Parms.bInIsDBNO = bInIsDBNO;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnPlayerGotSnowman
// (BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::OnPlayerGotSnowman()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnPlayerGotSnowman");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.ShowFakeActor
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::ShowFakeActor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "ShowFakeActor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnClientExitVolume_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     Client                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AFortVolume*                      Volume                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::OnClientExitVolume_Event_0(class APlayerState* Client, class AFortVolume* Volume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnClientExitVolume_Event_0");

	Params::Athena_Player_SneakySnowmanV2_C_OnClientExitVolume_Event_0 Parms{};

	Parms.Client = Client;
	Parms.Volume = Volume;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.StateChangedDelegate_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortMinigame*                    Minigame                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortMinigameState                      MinigameState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::StateChangedDelegate_Event_0(class AFortMinigame* Minigame, EFortMinigameState MinigameState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "StateChangedDelegate_Event_0");

	Params::Athena_Player_SneakySnowmanV2_C_StateChangedDelegate_Event_0 Parms{};

	Parms.Minigame = Minigame;
	Parms.MinigameState = MinigameState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.SetSnowmanHidden
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Hidden                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InstantOnAll                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::SetSnowmanHidden(bool Hidden, bool InstantOnAll)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "SetSnowmanHidden");

	Params::Athena_Player_SneakySnowmanV2_C_SetSnowmanHidden Parms{};

	Parms.Hidden = Hidden;
	Parms.InstantOnAll = InstantOnAll;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.SetPlayerHidden
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PlayerHidden_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::SetPlayerHidden(bool PlayerHidden_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "SetPlayerHidden");

	Params::Athena_Player_SneakySnowmanV2_C_SetPlayerHidden Parms{};

	Parms.PlayerHidden_0 = PlayerHidden_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.ToggleFakeSnowman
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ToggleFakeOn                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HidePlayerIfTrue                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FVector&                   CrouchedLoc                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    RotateToGround_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    SetPoppingOut                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::ToggleFakeSnowman(bool ToggleFakeOn, bool HidePlayerIfTrue, const struct FVector& CrouchedLoc, bool RotateToGround_0, bool SetPoppingOut)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "ToggleFakeSnowman");

	Params::Athena_Player_SneakySnowmanV2_C_ToggleFakeSnowman Parms{};

	Parms.ToggleFakeOn = ToggleFakeOn;
	Parms.HidePlayerIfTrue = HidePlayerIfTrue;
	Parms.CrouchedLoc = std::move(CrouchedLoc);
	Parms.RotateToGround_0 = RotateToGround_0;
	Parms.SetPoppingOut = SetPoppingOut;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.SetPrevLocation
// (BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::SetPrevLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "SetPrevLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnEnterVehicle
// (BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::OnEnterVehicle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnEnterVehicle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.RotateToStraight
// (BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::RotateToStraight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "RotateToStraight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.RotateToGround
// (BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::RotateToGround()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "RotateToGround");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.StopRotatingFake
// (BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::StopRotatingFake()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "StopRotatingFake");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnInteractWithFake
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class AFortPawn*                  InteractingPawn                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::OnInteractWithFake(const class AFortPawn* InteractingPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnInteractWithFake");

	Params::Athena_Player_SneakySnowmanV2_C_OnInteractWithFake Parms{};

	Parms.InteractingPawn = InteractingPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.JustAttached
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::JustAttached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "JustAttached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.SetFakeActor
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AAthena_Fake_SneakySnowmanV2_C*   FakeActor_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::SetFakeActor(class AAthena_Fake_SneakySnowmanV2_C* FakeActor_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "SetFakeActor");

	Params::Athena_Player_SneakySnowmanV2_C_SetFakeActor Parms{};

	Parms.FakeActor_0 = FakeActor_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.ToggleFakeSnowman_Multicast
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ToggleFakeOn                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FVector&                   CrouchedLoc                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    RotateToGround                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    SetPoppingOut                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::ToggleFakeSnowman_Multicast(bool ToggleFakeOn, const struct FVector& CrouchedLoc, bool RotateToGround, bool SetPoppingOut)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "ToggleFakeSnowman_Multicast");

	Params::Athena_Player_SneakySnowmanV2_C_ToggleFakeSnowman_Multicast Parms{};

	Parms.ToggleFakeOn = ToggleFakeOn;
	Parms.CrouchedLoc = std::move(CrouchedLoc);
	Parms.RotateToGround = RotateToGround;
	Parms.SetPoppingOut = SetPoppingOut;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.MovementUpdated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   OldLocation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   OldVelocity                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::MovementUpdated(float DeltaSeconds, const struct FVector& OldLocation, const struct FVector& OldVelocity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "MovementUpdated");

	Params::Athena_Player_SneakySnowmanV2_C_MovementUpdated Parms{};

	Parms.DeltaSeconds = DeltaSeconds;
	Parms.OldLocation = std::move(OldLocation);
	Parms.OldVelocity = std::move(OldVelocity);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.Destroy
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::Destroy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "Destroy");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.StopHiding
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    LaunchPlayer                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::StopHiding(bool LaunchPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "StopHiding");

	Params::Athena_Player_SneakySnowmanV2_C_StopHiding Parms{};

	Parms.LaunchPlayer = LaunchPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.SpawnProp
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PlayMontage                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    RemoveTags_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::SpawnProp(bool PlayMontage, bool RemoveTags_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "SpawnProp");

	Params::Athena_Player_SneakySnowmanV2_C_SpawnProp Parms{};

	Parms.PlayMontage = PlayMontage;
	Parms.RemoveTags_0 = RemoveTags_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.Destroyed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DestroyedActor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::Destroyed(class AActor* DestroyedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "Destroyed");

	Params::Athena_Player_SneakySnowmanV2_C_Destroyed Parms{};

	Parms.DestroyedActor = DestroyedActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.SpawnEffects
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::SpawnEffects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "SpawnEffects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.Wobble
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Strength                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    MoveUpAndDown                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::Wobble(float Strength, bool MoveUpAndDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "Wobble");

	Params::Athena_Player_SneakySnowmanV2_C_Wobble Parms{};

	Parms.Strength = Strength;
	Parms.MoveUpAndDown = MoveUpAndDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.CrouchedCheck
// (BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::CrouchedCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "CrouchedCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnDeathServer
// (BlueprintAuthorityOnly, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTagContainer&     DamageTags                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FVector&                   Momentum                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                HitInfo                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class AController*                      InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayEffectContextHandle&EffectContext                                          (BlueprintVisible, BlueprintReadOnly, Parm)

void AAthena_Player_SneakySnowmanV2_C::OnDeathServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnDeathServer");

	Params::Athena_Player_SneakySnowmanV2_C_OnDeathServer Parms{};

	Parms.Damage = Damage;
	Parms.DamageTags = std::move(DamageTags);
	Parms.Momentum = std::move(Momentum);
	Parms.HitInfo = std::move(HitInfo);
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;
	Parms.EffectContext = std::move(EffectContext);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnDamageServer
// (BlueprintAuthorityOnly, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTagContainer&     DamageTags                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FVector&                   Momentum                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                HitInfo                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class AController*                      InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayEffectContextHandle&EffectContext                                          (BlueprintVisible, BlueprintReadOnly, Parm)

void AAthena_Player_SneakySnowmanV2_C::OnDamageServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnDamageServer");

	Params::Athena_Player_SneakySnowmanV2_C_OnDamageServer Parms{};

	Parms.Damage = Damage;
	Parms.DamageTags = std::move(DamageTags);
	Parms.Momentum = std::move(Momentum);
	Parms.HitInfo = std::move(HitInfo);
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;
	Parms.EffectContext = std::move(EffectContext);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnCompleted_260935FE4E6B93550ACE848A0EA63F7B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::OnCompleted_260935FE4E6B93550ACE848A0EA63F7B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnCompleted_260935FE4E6B93550ACE848A0EA63F7B");

	Params::Athena_Player_SneakySnowmanV2_C_OnCompleted_260935FE4E6B93550ACE848A0EA63F7B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnBlendOut_260935FE4E6B93550ACE848A0EA63F7B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::OnBlendOut_260935FE4E6B93550ACE848A0EA63F7B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnBlendOut_260935FE4E6B93550ACE848A0EA63F7B");

	Params::Athena_Player_SneakySnowmanV2_C_OnBlendOut_260935FE4E6B93550ACE848A0EA63F7B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnInterrupted_260935FE4E6B93550ACE848A0EA63F7B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::OnInterrupted_260935FE4E6B93550ACE848A0EA63F7B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnInterrupted_260935FE4E6B93550ACE848A0EA63F7B");

	Params::Athena_Player_SneakySnowmanV2_C_OnInterrupted_260935FE4E6B93550ACE848A0EA63F7B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnNotifyBegin_260935FE4E6B93550ACE848A0EA63F7B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::OnNotifyBegin_260935FE4E6B93550ACE848A0EA63F7B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnNotifyBegin_260935FE4E6B93550ACE848A0EA63F7B");

	Params::Athena_Player_SneakySnowmanV2_C_OnNotifyBegin_260935FE4E6B93550ACE848A0EA63F7B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnNotifyEnd_260935FE4E6B93550ACE848A0EA63F7B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Player_SneakySnowmanV2_C::OnNotifyEnd_260935FE4E6B93550ACE848A0EA63F7B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnNotifyEnd_260935FE4E6B93550ACE848A0EA63F7B");

	Params::Athena_Player_SneakySnowmanV2_C_OnNotifyEnd_260935FE4E6B93550ACE848A0EA63F7B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.UpDOwn__UpdateFunc
// (BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::UpDOwn__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "UpDOwn__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.UpDOwn__FinishedFunc
// (BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::UpDOwn__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "UpDOwn__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.RotateToGroundTimeline__UpdateFunc
// (BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::RotateToGroundTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "RotateToGroundTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.RotateToGroundTimeline__FinishedFunc
// (BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::RotateToGroundTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "RotateToGroundTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.DropToFloor__UpdateFunc
// (BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::DropToFloor__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "DropToFloor__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.DropToFloor__FinishedFunc
// (BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::DropToFloor__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "DropToFloor__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.AdjustSnowman__UpdateFunc
// (BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::AdjustSnowman__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "AdjustSnowman__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.AdjustSnowman__FinishedFunc
// (BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::AdjustSnowman__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "AdjustSnowman__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.CheckIfCanJumpOut
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          InteractingPawn                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   CanInteract                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::CheckIfCanJumpOut(class UObject* InteractingPawn, bool* CanInteract)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "CheckIfCanJumpOut");

	Params::Athena_Player_SneakySnowmanV2_C_CheckIfCanJumpOut Parms{};

	Parms.InteractingPawn = InteractingPawn;

	UObject::ProcessEvent(Func, &Parms);

	if (CanInteract != nullptr)
		*CanInteract = Parms.CanInteract;
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.GetCrouchedLoc
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector AAthena_Player_SneakySnowmanV2_C::GetCrouchedLoc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "GetCrouchedLoc");

	Params::Athena_Player_SneakySnowmanV2_C_GetCrouchedLoc Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnStartedUsingFake
// (Public, BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::OnStartedUsingFake()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnStartedUsingFake");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnStoppedUsingFake
// (Public, BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::OnStoppedUsingFake()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnStoppedUsingFake");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnWeaponChange
// (Public, BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::OnWeaponChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnWeaponChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.GetFakeRotation
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FRotator                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

struct FRotator AAthena_Player_SneakySnowmanV2_C::GetFakeRotation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "GetFakeRotation");

	Params::Athena_Player_SneakySnowmanV2_C_GetFakeRotation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnRep_SelfHidden
// (BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::OnRep_SelfHidden()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnRep_SelfHidden");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnRep_PlayerHidden
// (BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::OnRep_PlayerHidden()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnRep_PlayerHidden");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnBeginInteractWithSphere
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::OnBeginInteractWithSphere()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnBeginInteractWithSphere");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.OnInterruptInteractWithSphere
// (Public, BlueprintCallable, BlueprintEvent)

void AAthena_Player_SneakySnowmanV2_C::OnInterruptInteractWithSphere()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "OnInterruptInteractWithSphere");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.CheckForClipping_
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Clipping                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::CheckForClipping_(bool* Clipping)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "CheckForClipping_");

	Params::Athena_Player_SneakySnowmanV2_C_CheckForClipping_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Clipping != nullptr)
		*Clipping = Parms.Clipping;
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.FlattestHitResult
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FHitResult>&              NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
// struct FHitResult*                      Flattest                                               (Parm, OutParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AAthena_Player_SneakySnowmanV2_C::FlattestHitResult(TArray<struct FHitResult>& NewParam, struct FHitResult* Flattest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "FlattestHitResult");

	Params::Athena_Player_SneakySnowmanV2_C_FlattestHitResult Parms{};

	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);

	NewParam = std::move(Parms.NewParam);

	if (Flattest != nullptr)
		*Flattest = std::move(Parms.Flattest);
}


// Function Athena_Player_SneakySnowmanV2.Athena_Player_SneakySnowmanV2_C.IsMeshHeightScalePositive
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   bReturnValue                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthena_Player_SneakySnowmanV2_C::IsMeshHeightScalePositive(bool* bReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_Player_SneakySnowmanV2_C", "IsMeshHeightScalePositive");

	Params::Athena_Player_SneakySnowmanV2_C_IsMeshHeightScalePositive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bReturnValue != nullptr)
		*bReturnValue = Parms.bReturnValue;
}

}

