#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AthenaBoundActionButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "CommonInput_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaBoundActionButton.AthenaBoundActionButton_C
// 0x0018 (0x0BE8 - 0x0BD0)
class UAthenaBoundActionButton_C final : public UFortBoundActionButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BD0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                ContentBorder;                                     // 0x0BD8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                              InputActionIconScale;                              // 0x0BE0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void UpdateInputActionIconSize();
	void Construct();
	void ExecuteUbergraph_AthenaBoundActionButton(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaBoundActionButton_C">();
	}
	static class UAthenaBoundActionButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaBoundActionButton_C>();
	}
};

}

