#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_HeldObject_Generic_Component

#include "Basic.hpp"

#include "B_HeldObject_Generic_Component_classes.hpp"
#include "B_HeldObject_Generic_Component_parameters.hpp"


namespace SDK
{

// Function B_HeldObject_Generic_Component.B_HeldObject_Generic_Component_C.ExecuteUbergraph_B_HeldObject_Generic_Component
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_HeldObject_Generic_Component_C::ExecuteUbergraph_B_HeldObject_Generic_Component(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_HeldObject_Generic_Component_C", "ExecuteUbergraph_B_HeldObject_Generic_Component");

	Params::B_HeldObject_Generic_Component_C_ExecuteUbergraph_B_HeldObject_Generic_Component Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_HeldObject_Generic_Component.B_HeldObject_Generic_Component_C.OnWeaponAttached
// (Event, Public, BlueprintEvent)

void AB_HeldObject_Generic_Component_C::OnWeaponAttached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_HeldObject_Generic_Component_C", "OnWeaponAttached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_HeldObject_Generic_Component.B_HeldObject_Generic_Component_C.K2_OnUnEquip
// (Event, Public, BlueprintEvent)

void AB_HeldObject_Generic_Component_C::K2_OnUnEquip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_HeldObject_Generic_Component_C", "K2_OnUnEquip");

	UObject::ProcessEvent(Func, nullptr);
}

}

