#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_Pickups_Default

#include "Basic.hpp"

#include "B_Pickups_Default_classes.hpp"
#include "B_Pickups_Default_parameters.hpp"


namespace SDK
{

// Function B_Pickups_Default.B_Pickups_Default_C.ExecuteUbergraph_B_Pickups_Default
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Pickups_Default_C::ExecuteUbergraph_B_Pickups_Default(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Pickups_Default_C", "ExecuteUbergraph_B_Pickups_Default");

	Params::B_Pickups_Default_C_ExecuteUbergraph_B_Pickups_Default Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Pickups_Default.B_Pickups_Default_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_Pickups_Default_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Pickups_Default_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Pickups_Default.B_Pickups_Default_C.HideBackgroundAndSpotlight
// (BlueprintCallable, BlueprintEvent)

void AB_Pickups_Default_C::HideBackgroundAndSpotlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Pickups_Default_C", "HideBackgroundAndSpotlight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Pickups_Default.B_Pickups_Default_C.OnPickedUp
// (Event, Public, BlueprintEvent)
// Parameters:
// class AFortPawn*                        PickupTarget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Pickups_Default_C::OnPickedUp(class AFortPawn* PickupTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Pickups_Default_C", "OnPickedUp");

	Params::B_Pickups_Default_C_OnPickedUp Parms{};

	Parms.PickupTarget = PickupTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Pickups_Default.B_Pickups_Default_C.OnTossed
// (Event, Public, BlueprintEvent)

void AB_Pickups_Default_C::OnTossed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Pickups_Default_C", "OnTossed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Pickups_Default.B_Pickups_Default_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AB_Pickups_Default_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Pickups_Default_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Pickups_Default.B_Pickups_Default_C.Setup Light
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Pickups_Default_C::Setup_Light()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Pickups_Default_C", "Setup Light");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Pickups_Default.B_Pickups_Default_C.Set Initial BKGD Param
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         Mid                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Pickups_Default_C::Set_Initial_BKGD_Param(class UMaterialInstanceDynamic* Mid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Pickups_Default_C", "Set Initial BKGD Param");

	Params::B_Pickups_Default_C_Set_Initial_BKGD_Param Parms{};

	Parms.Mid = Mid;

	UObject::ProcessEvent(Func, &Parms);
}

}

