#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BB_ToggleRadio

#include "Basic.hpp"

#include "SrirachaRanchUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BB_ToggleRadio.BB_ToggleRadio_C
// 0x0000 (0x0108 - 0x0108)
class UBB_ToggleRadio_C final : public UFortMobileActionButtonBehavior_ToggleRadio
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BB_ToggleRadio_C">();
	}
	static class UBB_ToggleRadio_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBB_ToggleRadio_C>();
	}
};

}

