#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_AISC_LOD_NPC_Base

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AISC_LOD_NPC_Base.BP_AISC_LOD_NPC_Base_C
// 0x0000 (0x00C0 - 0x00C0)
class UBP_AISC_LOD_NPC_Base_C : public UFortAthenaAISpawnerDataComponent_LOD
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AISC_LOD_NPC_Base_C">();
	}
	static class UBP_AISC_LOD_NPC_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AISC_LOD_NPC_Base_C>();
	}
};

}

