#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_PhoebePlayerController

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PhoebePlayerController.BP_PhoebePlayerController_C
// 0x0010 (0x0DF8 - 0x0DE8)
class ABP_PhoebePlayerController_C : public AFortAthenaAIBotController
{
public:
	class UAIPerceptionComponent*                 AIPerception;                                      // 0x0DE8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBlackboardComponent*                   Blackboard1;                                       // 0x0DF0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PhoebePlayerController_C">();
	}
	static class ABP_PhoebePlayerController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhoebePlayerController_C>();
	}
};

}

