#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BulletWhipTrackerComponent

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BulletWhipTrackerComponent.BulletWhipTrackerComponent_C
// 0x0000 (0x00F0 - 0x00F0)
class UBulletWhipTrackerComponent_C : public UBulletWhipTrackerComponentBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BulletWhipTrackerComponent_C">();
	}
	static class UBulletWhipTrackerComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBulletWhipTrackerComponent_C>();
	}
};

}

