#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FeedbackManagerAthena

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FeedbackManagerAthena.FeedbackManagerAthena_C
// 0x0008 (0x0360 - 0x0358)
class AFeedbackManagerAthena_C final : public AFortFeedbackManager
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FeedbackManagerAthena_C">();
	}
	static class AFeedbackManagerAthena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFeedbackManagerAthena_C>();
	}
};

}

