#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_FuelEquipped

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_FuelEquipped.GA_FuelEquipped_C
// 0x0008 (0x0AC0 - 0x0AB8)
class UGA_FuelEquipped_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AB8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_FuelEquipped(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_FuelEquipped_C">();
	}
	static class UGA_FuelEquipped_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_FuelEquipped_C>();
	}
};

}

