#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_SurfaceChange_Sand

#include "Basic.hpp"

#include "GA_SurfaceChange_Sand_classes.hpp"
#include "GA_SurfaceChange_Sand_parameters.hpp"


namespace SDK
{

// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.ExecuteUbergraph_GA_SurfaceChange_Sand
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_SurfaceChange_Sand_C::ExecuteUbergraph_GA_SurfaceChange_Sand(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "ExecuteUbergraph_GA_SurfaceChange_Sand");

	Params::GA_SurfaceChange_Sand_C_ExecuteUbergraph_GA_SurfaceChange_Sand Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.CancelCheckBurrowedAbilityActive
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::CancelCheckBurrowedAbilityActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "CancelCheckBurrowedAbilityActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.CheckBurrowedAbilityActive
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::CheckBurrowedAbilityActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "CheckBurrowedAbilityActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.BurrowedInvisibilityFailsafe
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::BurrowedInvisibilityFailsafe()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "BurrowedInvisibilityFailsafe");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.StartSnareMonitor
// (Event, Protected, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::StartSnareMonitor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "StartSnareMonitor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.OnPawnDestroyed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DestroyedActor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_SurfaceChange_Sand_C::OnPawnDestroyed(class AActor* DestroyedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "OnPawnDestroyed");

	Params::GA_SurfaceChange_Sand_C_OnPawnDestroyed Parms{};

	Parms.DestroyedActor = DestroyedActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.RepFromClientRemoveGEResetMeshHeight
// (Net, NetServer, BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::RepFromClientRemoveGEResetMeshHeight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "RepFromClientRemoveGEResetMeshHeight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.StartGameplayEventManager
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::StartGameplayEventManager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "StartGameplayEventManager");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.RemoveGEResetMeshHeight
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::RemoveGEResetMeshHeight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "RemoveGEResetMeshHeight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.UpdatePawnMeshHeightAdjust
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Reset                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_SurfaceChange_Sand_C::UpdatePawnMeshHeightAdjust(bool Reset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "UpdatePawnMeshHeightAdjust");

	Params::GA_SurfaceChange_Sand_C_UpdatePawnMeshHeightAdjust Parms{};

	Parms.Reset = Reset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.TryStartSnareStackMonitor
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::TryStartSnareStackMonitor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "TryStartSnareStackMonitor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.ResetSnareStackMonitor
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::ResetSnareStackMonitor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "ResetSnareStackMonitor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.MovementModeChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EMovementMode                           PrevMovementMode                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   PreviousCustomMode                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_SurfaceChange_Sand_C::MovementModeChanged(class ACharacter* Character, EMovementMode PrevMovementMode, uint8 PreviousCustomMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "MovementModeChanged");

	Params::GA_SurfaceChange_Sand_C_MovementModeChanged Parms{};

	Parms.Character = Character;
	Parms.PrevMovementMode = PrevMovementMode;
	Parms.PreviousCustomMode = PreviousCustomMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_SurfaceChange_Sand_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "K2_OnEndAbility");

	Params::GA_SurfaceChange_Sand_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.Added_E21473DC44E694E00ABDE9A9E9868B5E
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::Added_E21473DC44E694E00ABDE9A9E9868B5E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "Added_E21473DC44E694E00ABDE9A9E9868B5E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.Added_D67949EA4B1033677D0304BFF633D230
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::Added_D67949EA4B1033677D0304BFF633D230()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "Added_D67949EA4B1033677D0304BFF633D230");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.Added_8829590246932C80B18459A512ECD766
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::Added_8829590246932C80B18459A512ECD766()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "Added_8829590246932C80B18459A512ECD766");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.Added_709625FA42BD6074A8B324B182388B50
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::Added_709625FA42BD6074A8B324B182388B50()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "Added_709625FA42BD6074A8B324B182388B50");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.EventReceived_CE83B58349BB8A01393C3494113A5EC8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_SurfaceChange_Sand_C::EventReceived_CE83B58349BB8A01393C3494113A5EC8(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "EventReceived_CE83B58349BB8A01393C3494113A5EC8");

	Params::GA_SurfaceChange_Sand_C_EventReceived_CE83B58349BB8A01393C3494113A5EC8 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.Added_73CCC815473BDF85DA373384D45E2E8A
// (BlueprintCallable, BlueprintEvent)

void UGA_SurfaceChange_Sand_C::Added_73CCC815473BDF85DA373384D45E2E8A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "Added_73CCC815473BDF85DA373384D45E2E8A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.EventReceived_5D2F39E24252C3B3DCD2B78E038DCD75
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_SurfaceChange_Sand_C::EventReceived_5D2F39E24252C3B3DCD2B78E038DCD75(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "EventReceived_5D2F39E24252C3B3DCD2B78E038DCD75");

	Params::GA_SurfaceChange_Sand_C_EventReceived_5D2F39E24252C3B3DCD2B78E038DCD75 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.EventReceived_DD01A4BF47D0311DCB281E96A78ABD58
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_SurfaceChange_Sand_C::EventReceived_DD01A4BF47D0311DCB281E96A78ABD58(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "EventReceived_DD01A4BF47D0311DCB281E96A78ABD58");

	Params::GA_SurfaceChange_Sand_C_EventReceived_DD01A4BF47D0311DCB281E96A78ABD58 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.OnChange_0EF820D3457F6F827DD19EB3B581F798
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FActiveGameplayEffectHandle&Handle                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// int32                                   NewCount                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OldCount                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_SurfaceChange_Sand_C::OnChange_0EF820D3457F6F827DD19EB3B581F798(const struct FActiveGameplayEffectHandle& Handle, int32 NewCount, int32 OldCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "OnChange_0EF820D3457F6F827DD19EB3B581F798");

	Params::GA_SurfaceChange_Sand_C_OnChange_0EF820D3457F6F827DD19EB3B581F798 Parms{};

	Parms.Handle = std::move(Handle);
	Parms.NewCount = NewCount;
	Parms.OldCount = OldCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.InvalidHandle_0EF820D3457F6F827DD19EB3B581F798
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FActiveGameplayEffectHandle&Handle                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// int32                                   NewCount                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OldCount                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_SurfaceChange_Sand_C::InvalidHandle_0EF820D3457F6F827DD19EB3B581F798(const struct FActiveGameplayEffectHandle& Handle, int32 NewCount, int32 OldCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "InvalidHandle_0EF820D3457F6F827DD19EB3B581F798");

	Params::GA_SurfaceChange_Sand_C_InvalidHandle_0EF820D3457F6F827DD19EB3B581F798 Parms{};

	Parms.Handle = std::move(Handle);
	Parms.NewCount = NewCount;
	Parms.OldCount = OldCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.OnRemoved_A9C3352641C06BD58F07C285B5EE8AF5
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEffectRemovalInfo&GameplayEffectRemovalInfo                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_SurfaceChange_Sand_C::OnRemoved_A9C3352641C06BD58F07C285B5EE8AF5(const struct FGameplayEffectRemovalInfo& GameplayEffectRemovalInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "OnRemoved_A9C3352641C06BD58F07C285B5EE8AF5");

	Params::GA_SurfaceChange_Sand_C_OnRemoved_A9C3352641C06BD58F07C285B5EE8AF5 Parms{};

	Parms.GameplayEffectRemovalInfo = std::move(GameplayEffectRemovalInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SurfaceChange_Sand.GA_SurfaceChange_Sand_C.InvalidHandle_A9C3352641C06BD58F07C285B5EE8AF5
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEffectRemovalInfo&GameplayEffectRemovalInfo                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_SurfaceChange_Sand_C::InvalidHandle_A9C3352641C06BD58F07C285B5EE8AF5(const struct FGameplayEffectRemovalInfo& GameplayEffectRemovalInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SurfaceChange_Sand_C", "InvalidHandle_A9C3352641C06BD58F07C285B5EE8AF5");

	Params::GA_SurfaceChange_Sand_C_InvalidHandle_A9C3352641C06BD58F07C285B5EE8AF5 Parms{};

	Parms.GameplayEffectRemovalInfo = std::move(GameplayEffectRemovalInfo);

	UObject::ProcessEvent(Func, &Parms);
}

}

