#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_IceGrenade_Freeze_Deimos

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_IceGrenade_Freeze_Deimos.GE_IceGrenade_Freeze_Deimos_C
// 0x0000 (0x0800 - 0x0800)
class UGE_IceGrenade_Freeze_Deimos_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_IceGrenade_Freeze_Deimos_C">();
	}
	static class UGE_IceGrenade_Freeze_Deimos_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_IceGrenade_Freeze_Deimos_C>();
	}
};

}

