#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: HydrogenUI

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class HydrogenUI.HydrogenWidgetBase
// 0x0008 (0x0320 - 0x0318)
class UHydrogenWidgetBase final : public ULTMWidgetBase
{
public:
	class AFortAthenaMutator_Hydrogen*            CachedHydrogenMutator;                             // 0x0318(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void MutatorReady(const class AFortAthenaMutator_Hydrogen* MutatorActor);
	void OnMutatorAvailable(class AFortGameplayMutator* MutatorActor);

	float GetCaptureProgressPercent(const class AHydrogenObjectiveActor* InObjective) const;
	class AFortAthenaMutator_Hydrogen* GetHydrogenMutator() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"HydrogenWidgetBase">();
	}
	static class UHydrogenWidgetBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHydrogenWidgetBase>();
	}
};

}

