#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Math_Vector4_V

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// SolarisGeneratedClass Math_Vector4_V.Vector4_V
// 0x0010 (0x0038 - 0x0028)
class UVector4_V final : public UObject
{
public:
	float                                         __verse_0x6F57CF8F_x;                              // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __verse_0x0A307337_y;                              // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __verse_0xE49FC625_z;                              // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __verse_0x3947ACD7_w;                              // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UVector4_V* Create(float __verse_0x3205F605_inX, float __verse_0x57624ABD_inY, float __verse_0xB9CDFFAF_inZ, float __verse_0x6415955D_inW);
	static class UVector4_V* createZero();

	void _InitCDO();
	void _InitInstance();
	uint8 Equals(class UVector4_V* __verse_0x5C20106F_v, float __verse_0xB4A6AEEC_tolerance);
	class FString ToString();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Vector4_V">();
	}
	static class UVector4_V* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVector4_V>();
	}
};

}

