#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MiniCraftingIngredientListEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "CommonInput_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MiniCraftingIngredientListEntry.MiniCraftingIngredientListEntry_C
// 0x0010 (0x02C0 - 0x02B0)
class UMiniCraftingIngredientListEntry_C final : public UFortItemQuantityListEntryBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UItemCount_C*                           ItemCountWidget;                                   // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UWidget* Get_ItemCountWidget_ToolTipWidget();
	void RefreshBeingPreviewed();
	void Refresh();
	void HandleDifferentItemOrQuantitySetBP(const bool IsBeingReset);
	void PreviewStarted();
	void PreviewEnded();
	void RefreshListEntry();
	void ExecuteUbergraph_MiniCraftingIngredientListEntry(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MiniCraftingIngredientListEntry_C">();
	}
	static class UMiniCraftingIngredientListEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMiniCraftingIngredientListEntry_C>();
	}
};

}

