#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MissionGen_Cobalt_Small_Test

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MissionGen_Cobalt_Small_Test.MissionGen_Cobalt_Small_Test_C
// 0x0000 (0x06C8 - 0x06C8)
class UMissionGen_Cobalt_Small_Test_C final : public UFortMissionGenerator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MissionGen_Cobalt_Small_Test_C">();
	}
	static class UMissionGen_Cobalt_Small_Test_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionGen_Cobalt_Small_Test_C>();
	}
};

}

