#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: PhosphorusUI

#include "Basic.hpp"

#include "PhosphorusUI_classes.hpp"
#include "PhosphorusUI_parameters.hpp"


namespace SDK
{

// Function PhosphorusUI.PhosphorusWidgetBase.MutatorReady
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UPhosphorusWidgetBase::MutatorReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusWidgetBase", "MutatorReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PhosphorusUI.PhosphorusWidgetBase.OnMutatorAvailable
// (Native, Protected, BlueprintCallable)
// Parameters:
// class AFortGameplayMutator*             MutatorActor                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPhosphorusWidgetBase::OnMutatorAvailable(class AFortGameplayMutator* MutatorActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusWidgetBase", "OnMutatorAvailable");

	Params::PhosphorusWidgetBase_OnMutatorAvailable Parms{};

	Parms.MutatorActor = MutatorActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhosphorusUI.PhosphorusWidgetBase.SetAvatarImageFromPlayerState
// (Final, Native, Protected, BlueprintCallable)
// Parameters:
// const class AFortPlayerStateAthena*     PlayerState                                            (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UFortLazyImage*                   AvatarImage                                            (Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPhosphorusWidgetBase::SetAvatarImageFromPlayerState(const class AFortPlayerStateAthena* PlayerState, class UFortLazyImage* AvatarImage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusWidgetBase", "SetAvatarImageFromPlayerState");

	Params::PhosphorusWidgetBase_SetAvatarImageFromPlayerState Parms{};

	Parms.PlayerState = PlayerState;
	Parms.AvatarImage = AvatarImage;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhosphorusUI.PhosphorusWidgetBase.GetPhosphorusMutator
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class AFortAthenaMutator_Phosphorus*    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AFortAthenaMutator_Phosphorus* UPhosphorusWidgetBase::GetPhosphorusMutator() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusWidgetBase", "GetPhosphorusMutator");

	Params::PhosphorusWidgetBase_GetPhosphorusMutator Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhosphorusUI.PhosphorusEndOfRoundWidget.FadeOutScreen
// (Final, Native, Protected, BlueprintCallable)

void UPhosphorusEndOfRoundWidget::FadeOutScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusEndOfRoundWidget", "FadeOutScreen");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhosphorusUI.PhosphorusEndOfRoundWidget.OnNewRoundStarted
// (Event, Protected, BlueprintEvent)

void UPhosphorusEndOfRoundWidget::OnNewRoundStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusEndOfRoundWidget", "OnNewRoundStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PhosphorusUI.PhosphorusEndOfRoundWidget.OnPhosphorusPhaseChanged
// (Final, Native, Protected)
// Parameters:
// class AFortAthenaMutator_Phosphorus*    PhosphorusMutator                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EPhosphorusPhase                        NewPhase                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPhosphorusEndOfRoundWidget::OnPhosphorusPhaseChanged(class AFortAthenaMutator_Phosphorus* PhosphorusMutator, EPhosphorusPhase NewPhase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusEndOfRoundWidget", "OnPhosphorusPhaseChanged");

	Params::PhosphorusEndOfRoundWidget_OnPhosphorusPhaseChanged Parms{};

	Parms.PhosphorusMutator = PhosphorusMutator;
	Parms.NewPhase = NewPhase;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhosphorusUI.PhosphorusEndOfRoundWidget.SetWidgetVisibility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bNewVisibility                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPhosphorusEndOfRoundWidget::SetWidgetVisibility(bool bNewVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusEndOfRoundWidget", "SetWidgetVisibility");

	Params::PhosphorusEndOfRoundWidget_SetWidgetVisibility Parms{};

	Parms.bNewVisibility = bNewVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PhosphorusUI.PhosphorusHUDWidget.OnPhosphorusEnemySquadWiped_BP
// (Event, Protected, BlueprintEvent)

void UPhosphorusHUDWidget::OnPhosphorusEnemySquadWiped_BP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusHUDWidget", "OnPhosphorusEnemySquadWiped_BP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PhosphorusUI.PhosphorusHUDWidget.OnPhosphorusLocalSquadWiped_BP
// (Event, Protected, BlueprintEvent)

void UPhosphorusHUDWidget::OnPhosphorusLocalSquadWiped_BP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusHUDWidget", "OnPhosphorusLocalSquadWiped_BP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PhosphorusUI.PhosphorusHUDWidget.OnPhosphorusPlayerEliminated_BP
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AFortPlayerStateAthena*           PlayerEliminated                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPhosphorusHUDWidget::OnPhosphorusPlayerEliminated_BP(class AFortPlayerStateAthena* PlayerEliminated)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusHUDWidget", "OnPhosphorusPlayerEliminated_BP");

	Params::PhosphorusHUDWidget_OnPhosphorusPlayerEliminated_BP Parms{};

	Parms.PlayerEliminated = PlayerEliminated;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PhosphorusUI.PhosphorusSquadWipedWidget.HandleSquadWipedVisibilityChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bNewVisibility                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPhosphorusSquadWipedWidget::HandleSquadWipedVisibilityChanged(bool bNewVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusSquadWipedWidget", "HandleSquadWipedVisibilityChanged");

	Params::PhosphorusSquadWipedWidget_HandleSquadWipedVisibilityChanged Parms{};

	Parms.bNewVisibility = bNewVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PhosphorusUI.PhosphorusSquadWipedWidget.OnLocalPlayerSquadWiped
// (Final, Native, Protected)

void UPhosphorusSquadWipedWidget::OnLocalPlayerSquadWiped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PhosphorusSquadWipedWidget", "OnLocalPlayerSquadWiped");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

