#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: TextStyle_Button_Outline

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Button-Outline.TextStyle-Button-Outline_C
// 0x0000 (0x0148 - 0x0148)
class UTextStyle_Button_Outline_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Button-Outline_C">();
	}
	static class UTextStyle_Button_Outline_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_Button_Outline_C>();
	}
};

}

