#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: TextStyle_Base_S_B_Black

#include "Basic.hpp"

#include "TextStyle_Base_S_B_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-S-B-Black.TextStyle-Base-S-B-Black_C
// 0x0000 (0x0148 - 0x0148)
class UTextStyle_Base_S_B_Black_C final : public UTextStyle_Base_S_B_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-S-B-Black_C">();
	}
	static class UTextStyle_Base_S_B_Black_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_Base_S_B_Black_C>();
	}
};

}

