#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: VerseFortnite_VerseFortniteHacks

#include "Basic.hpp"


namespace SDK::Params
{

// Function VerseFortnite_VerseFortniteHacks.VerseFortniteHacks.getAllComponentsOfType
// 0x0020 (0x0020 - 0x0000)
struct VerseFortniteHacks_getAllComponentsOfType final
{
public:
	class UObject*                                __verse_0x9866B8E7_contextObject;                  // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 __verse_0x0F99A7FE_type;                           // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UEntityComponent*>               RetVal;                                            // 0x0010(0x0010)(Parm, OutParm, ReturnParm, HasGetValueTypeHash)
};

// Function VerseFortnite_VerseFortniteHacks.VerseFortniteHacks.RespawnPlayer
// 0x0010 (0x0010 - 0x0000)
struct VerseFortniteHacks_RespawnPlayer final
{
public:
	class UPlayerComponent*                       __verse_0x9F1D658F_player;                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayerStartComponent*                  __verse_0x9C54D01D_spawnPoint;                     // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

