#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: VerseFortnite_Player_PlayerInventory

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// SolarisGeneratedClass VerseFortnite_Player_PlayerInventory.PlayerInventory
// 0x0000 (0x0028 - 0x0028)
class UPlayerInventory final : public UObject
{
public:
	static void ClearDroppableItems(class UPlayerComponent* __verse_0x9F1D658F_player);
	static uint8 removeFromInventory(class UPlayerComponent* __verse_0x9F1D658F_player, const class FString& __verse_0x2FF42210_assetPath, int32 __verse_0x2867F112_quantity);
	static FOptionalProperty_ tryAddItemToInventory(class UPlayerComponent* __verse_0x9F1D658F_player, class UFortItemDefinition* __verse_0x555FC35C_itemDefinition, int32 __verse_0x2867F112_quantity, uint8 __verse_0x9D7D8947_notifyPlayerClient);
	static void tryAddToInventory(class UPlayerComponent* __verse_0x9F1D658F_player, const class FString& __verse_0x2FF42210_assetPath, int32 __verse_0x2867F112_quantity, uint8 __verse_0x9D7D8947_notifyPlayerClient);

	void _InitCDO();
	void _InitInstance();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PlayerInventory">();
	}
	static class UPlayerInventory* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerInventory>();
	}
};

}

