#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: VoiceChannelTransmitButton

#include "Basic.hpp"

#include "VoiceChannelTransmitButton_classes.hpp"
#include "VoiceChannelTransmitButton_parameters.hpp"


namespace SDK
{

// Function VoiceChannelTransmitButton.VoiceChannelTransmitButton_C.ExecuteUbergraph_VoiceChannelTransmitButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVoiceChannelTransmitButton_C::ExecuteUbergraph_VoiceChannelTransmitButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VoiceChannelTransmitButton_C", "ExecuteUbergraph_VoiceChannelTransmitButton");

	Params::VoiceChannelTransmitButton_C_ExecuteUbergraph_VoiceChannelTransmitButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VoiceChannelTransmitButton.VoiceChannelTransmitButton_C.OnUpdateVisuals
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsActive                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bTransmitting                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UVoiceChannelTransmitButton_C::OnUpdateVisuals(bool bIsActive, bool bTransmitting)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VoiceChannelTransmitButton_C", "OnUpdateVisuals");

	Params::VoiceChannelTransmitButton_C_OnUpdateVisuals Parms{};

	Parms.bIsActive = bIsActive;
	Parms.bTransmitting = bTransmitting;

	UObject::ProcessEvent(Func, &Parms);
}

}

