#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: VUI_VUIPlayerController

#include "Basic.hpp"


namespace SDK::Params
{

// Function VUI_VUIPlayerController.VUIPlayerController.Possess
// 0x0008 (0x0008 - 0x0000)
struct VUIPlayerController_Possess final
{
public:
	class UVUIBase*                               __verse_0x4F5E77FF_Obj;                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

